"""
starter_templates.py
Generates lightweight starter files (main.py, requirements.txt, n8n
workflow.json, and a Tailwind chat UI) bundled into every published repo.
"""


def build_main_py(topic: dict) -> str:
    title = topic["title"]
    return f'''"""
{title}
Starter automation script generated by Musfira AI.
Replace the placeholder logic below with your implementation.
"""

import requests

OLLAMA_URL = "http://localhost:11434/api/generate"


def query_local_llm(prompt: str, model: str = "llama3") -> str:
    resp = requests.post(
        OLLAMA_URL,
        json={{"model": model, "prompt": prompt, "stream": False}},
        timeout=60,
    )
    resp.raise_for_status()
    return resp.json().get("response", "")


def main() -> None:
    prompt = "Summarize the latest update on: {title}"
    print(query_local_llm(prompt))


if __name__ == "__main__":
    main()
'''


def build_requirements_txt() -> str:
    return "requests>=2.31.0\n"


def build_workflow_json(topic: dict) -> str:
    title = topic["title"].replace('"', "'")
    return f'''{{
  "name": "Musfira AI - {title}",
  "nodes": [
    {{
      "parameters": {{}},
      "id": "manual-trigger",
      "name": "Manual Trigger",
      "type": "n8n-nodes-base.manualTrigger",
      "typeVersion": 1,
      "position": [240, 300]
    }},
    {{
      "parameters": {{
        "url": "http://localhost:11434/api/generate",
        "method": "POST",
        "jsonParameters": true,
        "options": {{}},
        "bodyParametersJson": "{{\\"model\\": \\"llama3\\", \\"prompt\\": \\"Summarize: {title}\\", \\"stream\\": false}}"
      }},
      "id": "ollama-call",
      "name": "Query Ollama",
      "type": "n8n-nodes-base.httpRequest",
      "typeVersion": 3,
      "position": [460, 300]
    }}
  ],
  "connections": {{
    "Manual Trigger": {{
      "main": [[{{"node": "Query Ollama", "type": "main", "index": 0}}]]
    }}
  }}
}}
'''


def build_chat_ui_html(topic: dict) -> str:
    title = topic["title"]
    return f'''<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>{title} - Musfira AI</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.2.19/tailwind.min.css"></script>
</head>
<body class="bg-gray-900 text-gray-100 min-h-screen flex flex-col items-center justify-center p-4">
  <div class="w-full max-w-lg bg-gray-800 rounded-lg shadow-lg p-6">
    <h1 class="text-xl font-bold mb-4">{title}</h1>
    <div id="chat-log" class="space-y-2 h-80 overflow-y-auto mb-4 text-sm"></div>
    <div class="flex gap-2">
      <input id="chat-input" class="flex-1 rounded px-3 py-2 text-black" placeholder="Ask something..." />
      <button id="send-btn" class="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded">Send</button>
    </div>
    <p class="text-xs text-gray-400 mt-4">Powered by Musfira AI · local Ollama backend</p>
  </div>

  <script>
    const log = document.getElementById("chat-log");
    const input = document.getElementById("chat-input");
    const sendBtn = document.getElementById("send-btn");

    function appendMessage(role, text) {{
      const el = document.createElement("div");
      el.className = role === "user" ? "text-right text-blue-300" : "text-left text-gray-200";
      el.textContent = text;
      log.appendChild(el);
      log.scrollTop = log.scrollHeight;
    }}

    async function sendMessage() {{
      const prompt = input.value.trim();
      if (!prompt) return;
      appendMessage("user", prompt);
      input.value = "";
      try {{
        const res = await fetch("http://localhost:11434/api/generate", {{
          method: "POST",
          headers: {{ "Content-Type": "application/json" }},
          body: JSON.stringify({{ model: "llama3", prompt, stream: false }})
        }});
        const data = await res.json();
        appendMessage("assistant", data.response || "(no response)");
      }} catch (err) {{
        appendMessage("assistant", "Error: local Ollama server not reachable.");
      }}
    }}

    sendBtn.addEventListener("click", sendMessage);
    input.addEventListener("keydown", (e) => {{ if (e.key === "Enter") sendMessage(); }});
  </script>
</body>
</html>
'''
